apiVersion: v1
kind: Service
metadata:
  name: swe304-service
spec:
  type: NodePort
  selector:
    app: swe304
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
